# Generated by Django 5.2 on 2026-02-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphoto',
            name='name',
            field=models.CharField(default='', help_text='Название проекта', max_length=100),
        ),
    ]
