# Generated by Django 5.2 on 2026-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphoto',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Ссылка на сайт', null=True),
        ),
    ]
