# Generated by Django 5.2 on 2026-02-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectphoto_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphoto',
            name='link',
        ),
        migrations.RemoveField(
            model_name='projectphoto',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Ссылка на проект', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Без названия', help_text='Название проекта', max_length=100),
        ),
    ]
