# Generated by Django 5.2 on 2026-02-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_projectphoto_link_remove_projectphoto_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Слайд', help_text='Заголовок слайда', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание слайда', null=True)),
                ('image', models.ImageField(blank=True, help_text='Изображение для слайда', null=True, upload_to='carousel_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
