# Generated by Django 5.2 on 2026-02-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carouselslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslide',
            options={'verbose_name_plural': 'Слайды в карусели'},
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='order',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='title',
        ),
    ]
