# Generated by Django 5.2 on 2026-02-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carouselslide_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselSlide',
            new_name='AboutCarousel',
        ),
    ]
