# Generated by Django 5.2 on 2026-02-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_subservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
