# Generated by Django 5.2 on 2026-02-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.AddField(
            model_name='application',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Telegram'), ('email', 'Max'), ('messenger', 'Звонок')], default='phone', max_length=10, verbose_name='Предпочтительный способ связи'),
        ),
        migrations.AddField(
            model_name='application',
            name='privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(verbose_name='Описание проекта'),
        ),
    ]
