# Generated by Django 5.2 on 2026-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_application_email_application_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_method',
            field=models.CharField(choices=[('messenger', 'Telegram'), ('messenger', 'Max'), ('phone', 'Звонок')], default='phone', max_length=10, verbose_name='Предпочтительный способ связи'),
        ),
    ]
