# Generated by Django 5.2 on 2026-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_application_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_method',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'Max'), ('call', 'Звонок')], default='phone', max_length=10, verbose_name='Предпочтительный способ связи'),
        ),
    ]
