# Generated by Django 5.2 on 2026-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_application_contact_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcarousel',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutcarousel',
            name='image_desktop',
            field=models.ImageField(blank=True, help_text='Изображение для слайда на десктопе', null=True, upload_to='carousel_images/desktop'),
        ),
        migrations.AddField(
            model_name='aboutcarousel',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Изображение для слайда на мобильных устройствах', null=True, upload_to='carousel_images/mobile'),
        ),
    ]
