# Generated by Django 5.2 on 2026-03-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_aboutcarousel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectphoto',
            options={'ordering': ['order'], 'verbose_name': 'Фотография проекта', 'verbose_name_plural': 'Фотографии проектов'},
        ),
    ]
